### ISSUE TITLE
Problème de regex avec awk ?

### ISSUE THREAD

**Issue by eancelet** [arcolan/omniauth2-shibboleth#2]
https://github.com/arcolan/omniauth2-shibboleth/blob/f7f8927bae56d46491a0f106e6fb0ccd6f53e0ba/gitlab/o2s-install.sh#L227

Sur Ubuntu 22.04 cette ligne pose problème :
```
awk: warning: escape sequence `\(' treated as plain `('
awk: cmd. line:1: (FILENAME=/opt/gitlab/embedded/service/gitlab-rails/Gemfile.lock FNR=1) fatal: invalid regexp: Unmatched ( or \(: /  omniauth-saml (~> */
```

Par contre l'expression suivante fonctionne : 
`omniauth-saml \\\\(~> *`
(ne me demandez pas pourquoi)

**Comment by arcolan** [comment]
L'expression proposée fonctionne également sous Debian : https://github.com/arcolan/omniauth2-shibboleth/commit/def94777d408226f7d26c182b3d5f4cd4d337962
Merci @eancelet pour le retour !
